traindata<-read.csv("train.csv")
testData<-read.csv("test.csv")
head(traindata)
plot(density(traindata$Age,na.rm=TRUE))
plot(density(traindata$Fare,na.rm=TRUE))
plot(density(traindata$PassengerId,na.rm=TRUE))
plot(density(traindata$Survived,na.rm=TRUE))
plot(density(traindata$Fare,na.rm=TRUE))
counts<-table(traindata$Survived,traindata$Sex)
barplot(counts,xlab = "Gender",ylab = "Number of People",main = "survived")
counts[2]/(counts[1]+counts[2])
counts[4]/(counts[3]+counts[4])
Pclass_survival<-table(traindata$Survived,traindata$Pclass)
barplot(Pclass_survival,xlab="Cabin Class",ylab="Number of People",main="survived and deceased between male and female")
Pclass_survival[2]/(Pclass_survival[1]+Pclass_survival[2])
Pclass_survival[4]/(Pclass_survival[3]+Pclass_survival[4])
Pclass_survival[6]/(Pclass_survival[5]+Pclass_survival[6])
